import type { Metadata } from "next";
import Image from "next/image";
import { FaFacebookF, FaInstagram } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import "./globals.css";
import Navbar, { NavbarHeader } from "./Navbar";

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "DNA Kabar : Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased relative`}
      >
        <header className="hidden lg:block">
          <NavbarHeader />
        </header>

        <nav className='border-t-2 sticky top-0 z-50 bg-white border-theme-red w-full'>
          <Navbar />
        </nav>
        {children}
        <footer className="bg-theme-red mt-20 pt-5 lg:text-end text-center">
          <div className="container max-w-[1200px] lg:px-5 px-2 flex items-center gap-10 flex-col lg:flex-row justify-between">
            <Image src={'https://www.ratopati.com/build/img/logo.png'} alt="logo" width={200} height={200} />
            <div className="flex flex-col gap-1">
              <p className="text-white">
                © 2025 Copyright Discovery News Network | All rights reserved.
              </p>
              <p className="text-white">
                स्रोतहरू खुलाइएका बाहेक रातोपाटीमा प्रकाशित सम्पूर्ण सामग्रीहरू डिस्कवरी न्युज नेटवर्कका सम्पत्ति हुन् ।
              </p>
            </div>

            <div className="flex items-center text-white gap-3">
              <div className="bg-white/35 grid place-content-center  rounded-full size-[50px]">
                <FaFacebookF size={25} />
              </div>
              <div className="bg-white/35 grid place-content-center  rounded-full size-[50px]">
                <FaXTwitter size={25} />
              </div>
              <div className="bg-white/35 grid place-content-center  rounded-full size-[50px]">
                <FaInstagram size={25} />
              </div>
            </div>
          </div>
          <div className="bg-red-900  mt-5 py-2">
            <div className="container max-w-[1200px] lg:px-5 px-2">
              <p className="text-white">Design & Developed by: <span className="text-2xl font-semibold">Spell innovation</span></p>
            </div>
          </div>
        </footer>

      </body>
    </html>
  );
}
